# Generated by Django 3.2.11 on 2022-04-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quiz', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dlevel',
            fields=[
                ('dl_id', models.AutoField(db_column='dl_id', primary_key=True, serialize=False)),
                ('dl_title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lg_id', models.AutoField(db_column='qt_id', primary_key=True, serialize=False)),
                ('lg_title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_id', models.AutoField(db_column='qt_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='solution')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dlavel_qproto', to='exam.dlevel')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='language_qproto', to='exam.language')),
                ('qtype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qtype', to='Quiz.qtype')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.CharField(max_length=255, verbose_name='Answer Text')),
                ('is_right', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='language_answer', to='exam.language')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['id'],
            },
        ),
    ]
