# Generated by Django 3.2.11 on 2022-04-30 12:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('Quiz', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dlevel',
            fields=[
                ('dl_id', models.AutoField(db_column='dl_id', primary_key=True, serialize=False)),
                ('dl_title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lg_id', models.AutoField(db_column='lg_id', primary_key=True, serialize=False)),
                ('lg_title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='TestLayout',
            fields=[
                ('tl_id', models.AutoField(db_column='tl_id', primary_key=True, serialize=False)),
                ('tl_title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Testmake',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('te_id', models.AutoField(db_column='te_id', primary_key=True, serialize=False)),
                ('testName', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('noOfQuestions', models.PositiveIntegerField()),
                ('totalMarks', models.PositiveIntegerField(null=True)),
                ('hour', models.PositiveIntegerField()),
                ('minute', models.PositiveIntegerField()),
                ('testCategory', models.CharField(choices=[('Practice', 'Practice'), ('Examination', 'Examination')], default='1', max_length=20)),
                ('poolQuestion', models.BooleanField(default=False)),
                ('freeAvailable', models.BooleanField(default=False)),
                ('testShowFrom', models.DateTimeField(verbose_name='%d/%m/%y %H:%M')),
                ('testEndON', models.DateTimeField(blank=True, null=True)),
                ('testLayout', models.ForeignKey(db_column='test_layout', on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_TestLayout', to='QuizData.testlayout')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_user1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('ts_id', models.AutoField(db_column='te_id', primary_key=True, serialize=False)),
                ('sectionName', models.CharField(max_length=255)),
                ('hour', models.PositiveIntegerField(default=False)),
                ('minute', models.PositiveIntegerField(default=False)),
                ('allowedSectionSwitching', models.BooleanField(default=False)),
                ('skipSectionBeforeTimeOver', models.BooleanField(default=False)),
                ('studentChoice', models.BooleanField(default=False)),
                ('useSectionAsBreak', models.BooleanField(default=False)),
                ('showPreviousSection', models.BooleanField(default=False)),
                ('sectionInstruction', models.TextField(blank=True, default=None, null=True)),
                ('testmake', models.ForeignKey(db_column='testmake', on_delete=django.db.models.deletion.DO_NOTHING, related_name='testSeection_testMake', to='QuizData.testmake')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qu_id', models.AutoField(db_column='qu_id', primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=500, null=True)),
                ('difficulty', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlavel_question3', to='QuizData.dlevel')),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_question3', to='QuizData.language')),
                ('qtype', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qtype_question3', to='Quiz.qtype')),
                ('topic', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_question3', to='course.topic')),
                ('user', models.ForeignKey(db_column='user', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ques_user1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['qu_id'],
            },
        ),
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qd_id', models.AutoField(db_column='qd_id', default=None, primary_key=True, serialize=False)),
                ('question_para', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('question_text', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='description')),
                ('solution', ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='solution')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('qid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ques_qdes3', to='QuizData.question')),
                ('ques_lang', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_qdes3', to='QuizData.language')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(default=None, max_length=255, verbose_name='Answer Text')),
                ('is_right', models.BooleanField(default=False)),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_answer3', to='QuizData.language')),
                ('question', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices', to='QuizData.ques')),
            ],
        ),
    ]
