# Generated by Django 3.2.11 on 2022-04-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cr_id', models.AutoField(db_column='cr_id', primary_key=True, serialize=False)),
                ('cr_title', models.CharField(max_length=255, verbose_name='Title')),
                ('cr_slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('cr_short', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('cr_long', models.TextField(blank=True, null=True, verbose_name='Long description')),
                ('cr_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=255, verbose_name='Title')),
                ('category_slug', models.SlugField(max_length=255, null=True, verbose_name='slug')),
                ('category_short', models.TextField(blank=True, null=True, verbose_name='short description')),
                ('category_createddate', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(db_column='sub_id', primary_key=True, serialize=False)),
                ('sub_title', models.CharField(max_length=255, verbose_name='Title')),
                ('sub_slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('sub_short', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('sub_long', models.TextField(blank=True, null=True, verbose_name='Long description')),
                ('sub_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('sub_course', models.ManyToManyField(db_column='sub_course', related_name='subject', to='course.Course', verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('top_id', models.AutoField(db_column='top_id', primary_key=True, serialize=False)),
                ('top_title', models.CharField(max_length=255, verbose_name='Title')),
                ('top_slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('top_short', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('top_long', models.TextField(blank=True, null=True, verbose_name='Long description')),
                ('top_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('top_subject', models.ManyToManyField(db_column='top_subject', related_name='topics', to='course.Subject', verbose_name='Topic')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='cr_categ',
            field=models.ManyToManyField(db_column='cr_categ', related_name='courses', to='course.CourseCategory', verbose_name='Category'),
        ),
    ]
